### ISSUE TITLE
Username from URL is ignored

### ISSUE THREAD

**Issue by jerrinot** [questdb/questdb-connect#5]
It looks QuestDB-Connect ignores the username parsed from the URL and always defaults to "admin". 
This is caused by a wrong constant in our connect() function. 

See the screenshot:
<img width="1030" alt="image" src="https://github.com/questdb/questdb-connect/assets/158619/491c58d7-a9fa-4b37-9f26-a1fcd6aac0d4">

The line 94 should `get()` "user", not "username".

*Reproducer*
1. Open [hello_world.py](https://github.com/questdb/questdb-connect/blob/b106391d283aaf3bbcd5893844ae937e18638834/src/examples/hello_world.py#L46) and change the URL `("questdb://user:quest@localhost:8812/main")`
2. Run the Hello World example
3. Watch Connect to still use the `admin` username when connecting to QuestDB instead of `user` as specified in the URL. 

*Expected behaviour*
The username from the URL should be used. 

The fix is trivial, but I would send a PR with a fix, but I don't understand the test setup well enough to write a test for this.

**Comment by marregui** [comment]
release https://pypi.org/manage/project/questdb-connect/release/1.0.9/ should fix it.
