### ISSUE TITLE
Can't get table list

### ISSUE THREAD

**Issue by hnewcity** [questdb/questdb-connect#8]
Version: questdb-connect==1.0.10

I connected to the QuestDB, but there are some problems show tables when using SQL Lab or create datasets. Anyway, It can't  excute show tables query.

Thanks! 
<img width="1905" alt="截屏2023-10-26 上午1 51 05" src="https://github.com/questdb/questdb-connect/assets/17564645/e1cd270f-efa3-4ef4-a24d-8aa837627582">

**Comment by ATOLcapital** [comment]
Having the very same problem.

**Comment by ATOLcapital** [comment]
Hi @argshook @bluestreak01 is it a bug? Is it planned to solve it in near future?

**Comment by marregui** [comment]
hi, I can reproduce, I will be fixing it.

**Comment by marregui** [comment]
hi, thank you for reporting it, it has been fix now and released https://pypi.org/project/questdb-connect/1.0.11/ 

best regards

**Comment by razuro** [comment]
Hi, may I know what version of QuestDB and Superset that you're using? Because I can only try QuestDB v7.3.1 and v7.3.10, and the only questdb-connect that works for both is v0.0.54.
